### ISSUE TITLE
Create table for event in database and connect backend component accordingly

### ISSUE THREAD

**Issue by m5luo** [m5luo/cse110_study_scheduler_app#24]
- require that issue 2 is merged into main
- add table for events in database
- modify database when event is created/updated/deleted

**Comment by JonathanXiang** [comment]
Finished. Backend Methods of create, delete, and get/fetch are done for Calendar Events, SQLite Database is setup and connected to the backend events.

I also created the frontend utils as well as a basic Calendar Event creation form and display where you can delete. (I did this for the purpose of testing, but it will also likely be useful when putting the frontend and backend together)

**Comment by JonathanXiang** [comment]
Results in "Jonathan-Xiang" Branch
